export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const SET_USER_DATA = "SET_USER_DATA";
export const LOADING_CURRENT_SESSION = "LOADING_CURRENT_SESSION";

export const GET_SAVED_LOCATIONS = "GET_SAVED_LOCATIONS";
export const ADD_SAVED_LOCATION = "ADD_SAVED_LOCATION";
export const DELETE_SAVED_LOCATION = "DELETE_SAVED_LOCATION";

export const SET_SEARCHED_WEATHER = "SET_SEARCHED_WEATHER";
export const DELETE_SEARCHED_WEATHER = "DELETE_SEARCHED_WEATHER";

export const SET_SAVED_WEATHER = "SET_SAVED_WEATHER";
export const DELETE_SAVED_WEATHER = "DELETE_SAVED_WEATHER";

export const SAVE_WEATHER_LOCATION = "SAVE_WEATHER_LOCATION";

export const TOGGLE_TEMP_SCALE = "TOGGLE_TEMP_SCALE";
